// Generated by CoffeeScript 1.7.1
var Opticrop, inFile, opticrop, out;

Opticrop = require('./lib/opticrop.js');

opticrop = new Opticrop;

out = '/tmp/ocrop/cr_beautiful-girl-wallpapers-8.jpg';

inFile = '/tmp/ocrop/beautiful-girl-wallpapers-8.jpg';

opticrop.setImage(inFile).setWidth(100).setHeight(100).cropTo(out, function(err, data) {
  return console.log("***", err, data);
});
