// Generated by CoffeeScript 1.7.1
var Opticrop, async, inFile, opticrop, out, util;

Opticrop = require('./lib/opticrop.js');

async = require('async');

util = require('util');

opticrop = new Opticrop;

inFile = './images/example.jpg';

out = './images/example_cropped.jpg';

opticrop.setImage(inFile).setWidth(100).setHeight(100).cropTo(out, function(err, data) {
  return console.log("***", err, data);
});
