// Generated by CoffeeScript 1.7.1
var Opticrop, async, filesDir, inputFiles, opticrop, util;

Opticrop = require('./lib/opticrop.js');

async = require('async');

util = require('util');

inputFiles = ['example.jpg', 'example.png', 'example.gif'];

filesDir = "./images/";

opticrop = new Opticrop;

async.each(inputFiles, function(file, cb) {
  var inFile, outFile;
  console.time(file);
  inFile = "" + filesDir + file;
  outFile = "" + filesDir + "cropped_" + file;
  return opticrop.setImage(inFile).setWidth(100).setHeight(100).cropTo(outFile, function(err) {
    console.log("***", err);
    console.timeEnd(file);
    return cb(err);
  });
}, function(err) {
  if (err) {
    return console.log("Error: " + err);
  } else {
    return console.log("All files were cropped without erros");
  }
});
